<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('patients', function (Blueprint $table) {
            $table->id();

            // System-facing readable identifier, e.g. PAT-MAIN-2026-000001
            // Generated by App\Services\PatientNumberGenerator, never edited manually.
            $table->string('patient_number', 40)->unique();

            // Personal data
            $table->string('first_name', 100);
            $table->string('middle_name', 100)->nullable();
            $table->string('last_name', 100);
            $table->enum('gender', ['male', 'female']);
            $table->date('birth_date');
            $table->string('national_id', 50)->nullable()->unique();
            $table->string('phone', 20);
            $table->string('email', 150)->nullable();
            $table->text('address')->nullable();

            // System data
            // Branch where the patient was originally registered — informational only.
            // Does NOT restrict which branch may treat this patient (see appointments).
            $table->foreignId('registered_branch_id')
                ->constrained('branches')
                ->restrictOnDelete();
            $table->foreignId('created_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();
            $table->boolean('is_active')->default(true);

            $table->timestamps();
            $table->softDeletes();

            // Reception staff search by phone constantly — needs an index.
            $table->index('phone');
            $table->index(['last_name', 'first_name']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('patients');
    }
};
